# Copyright (c) 2015, NVIDIA CORPORATION.  All rights reserved.

language: python
python:
    2.7
compiler: gcc   # for Caffe
sudo: required  # for Caffe

before_install:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - export PATH=/home/travis/miniconda/bin:$PATH
script:
    nosetests -v --with-coverage
