# Copyright (c) 2015, NVIDIA CORPORATION.  All rights reserved.

language: python
python:
    2.7
compiler: gcc   # for Caffe
sudo: required  # for Caffe

before_install:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - export PATH=/home/travis/miniconda/bin:$PATH
install:
#    - conda install --yes gevent greenlet
     - echo line 1
     - time travis_wait sleep 900
     - echo line 2
script:
    nosetests -v --with-coverage
